### ISSUE TITLE
JAVA_HOME windows

### ISSUE THREAD

**Issue by DiscoDancer** [qreal/qreal-web#11]
В эту инструкцию по сборке (https://github.com/qreal/qreal-web/tree/master/Robots_diagram) можно добавить, что после установки jdk нужно убедиться, что JAVA_HOME указывает именно на JDK x86. С jdk x64 не получается.

**Comment by DiscoDancer** [comment]
Также нужно добавить системные переменные M2_HOME и MAVEN_HOME, значение которых = путь до папки apache mvn. Также нужно добавить в переменную path %M2_HOME%\bin . Моя версия ОСИ - Win 10 x64 Pro.

**Comment by DiscoDancer** [comment]
Также для облегчения жизни можно добавить ссылку на утилитку Rapid Environment для редактирования системных переменных.

**Comment by vladimir-zakharov** [comment]
Проверил на точно такой же ОС -- Win 10 x64 Pro. 
1) Все работает с JDK x64
2) Переменные M2_HOME и MAVEN_HOME не нужны, работает все, если правильно добавить в переменную %Path% путь до папки bin maven'a.
3) Для редактирования пары системных переменных, по-моему, будет лишним устанавливать какую-то утилиту, быстрее их изменить стандартными средствами.
