### ISSUE TITLE
Описание 

### ISSUE THREAD

**Issue by BDM30** [qreal/qreal-web#13]
Здраствуйте, делал все по [иструкции](https://github.com/qreal/qreal-web/wiki/%D0%9D%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D1%8B%D0%B5-%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%BE%D0%B9-(Windows)), у меня новая windows 10.
1. java_home путь дожен быть просто до jdk без /bin
2. отдельно еще пришлось доставить grunt через npm.

**Comment by vladimir-zakharov** [comment]
1. В инструкции и написано, что нужно создать системную переменную JAVA_HOME с путем, куда был установлен JDK. С bin нужно добавить в переменную Path.
2. Да, спасибо, добавил пункт.

**Comment by vladimir-zakharov** [comment]
1. Разделил на 2 пункта, чтобы было более очевидно.

**Comment by BDM30** [comment]
да, не заметил, спасибо :)
